### ISSUE TITLE
Latest code does not compile

### ISSUE THREAD

**Issue by pjcook** [percy/percy-xcui-swift#12]
The latest `lint fix` commit breaks the SDK. Instead of removing the `override` keyword, you should have swapped 

override public func viewDidLoad() {

for 

public override func viewDidLoad() {

<img width="1519" alt="Screenshot 2024-02-29 at 16 18 35" src="https://github.com/percy/percy-xcui-swift/assets/1152532/e5b12431-a137-44f4-8011-bb42dfb12828">

**Comment by ruixhuang** [comment]
+1

**Comment by pjcook** [comment]
I created this fork and committed the above change along with fixing all the code and syntax issues in the unit tests. I couldn't actually figure out how to run the tests successfully, but at least they compile now. 
https://github.com/pjcook/percy-xcui-swift

**Comment by prklm10** [comment]
Hi all, Sorry for late response. We have fixed this issue in #14.

**Comment by prklm10** [comment]
We are closing this issue.
